### PR TITLE
yardoc: for c bindings

### PR DESCRIPTION
**Pull request by stackmystack**
Addresses the documentation aspect of TreeStand [integration MR](https://github.com/Faveod/ruby-tree-sitter/pull/35).

- [x] C Bindings API
- [x] Ruby thin layer from `TreeSitter`
- [x] CI
  - [x] Generate
  - [x] Publish
- [x] README.md
- [x] Contributing.md
- [x] License

### CODE REVIEW

**Comment by DerekStride** [comment]
For C extensions we'd have to document in the RDoc style which is done via indentation: https://github.com/ruby/rdoc/blob/master/ExampleRDoc.rdoc#label-Verbatim+sections

> YARD supports the same syntax as RDoc for .c files. You can look at examples in Ruby source but it doesn't seem like there is any coherent documentation on this format.
> - https://github.com/lsegal/yard/issues/1281#issuecomment-544773924

**Comment by stackmystack** [comment]
Yes thanks for the pointers, I already started to fix them.

I also found some missing bindings (in `Input`).

Indentation helped in outputting the verbatim I wanted, but I was wondering how come you were able to get backticks work in TreeStand. I copied the yard condig locally, and I don't see anything special to begin with.

Alas, wraping with `+` did the job so I'll speed through the documentation and polish later.

**Comment by stackmystack** [comment]
I added the publishing part as a pure github action (vs pushing to a specific branch; it's a new feature in gh).

I still need to make 1 breaking change in `Node#[]` and `Node#fetch`, and this PR would be ready … I will add them here for simplicity. I'm allowing it to be breaking because we agreed on a `1.0` release post-merge …

**Comment by stackmystack** [comment]
I'm ready to rebase on top of your branch, either directly, or post-merge with master.

**Review by DerekStride — APPROVED** [review]
I think we can merge this right to main but maybe hold off till #35 has landed since it does reference the TreeStand API.

**Comment by stackmystack** [comment]
I am having issues reproducing the CI failure, after I managed to fix my environment (OS upgrade that went wrong).

I can't reproduce the CI error, and instead I am getting a different error:

1. CI: 2 of this branch's test are failing, introduced here by a commit.
2. Locally: A test from tree_stand: a pretty_printing test over the math parser.

Here's what I get locally:

```
 FAIL Utils::PrinterTest#test_pretty_printing_nodes (0.39s)
        --- expected
        +++ actual
        @@ -21,9 +21,9 @@
            left: (number)             | 9
            (\"*\")                      | *
            right: (\"(\")               | (
        -   (subtraction
        +   right: (subtraction
             left: (number)            | 10
             (\"-\")                     | -
             right: (number))          | 11.1
        -   (\")\"))))                   | )
        +   right: (\")\"))))            | )
         "
        …/test/tree_stand/utils/printer_test.rb:48:in `test_pretty_printing_nodes'
```
I would need more time to debug this, hopefully tomorrow.

**Pull request merged**
